export const badgesDict: { [key: string]: string } = {
  "Founder": "founder",
  "Retired Moderator": "modex",
  "Easter Egg": "eegg1",
  "Issues Author": "issuesauthor",
  "Postmaster": "acc_supporter_silver",
  "Postmaster-General": "acc_supporter",
  "Historical Resolution Author": "resauthorun",
  "General Assembly Resolution Author": "resauthorga",
  "Moderator": "mod",
  "Site Supporter": "acc_supporter_bronze"
}
export const trophiesDict: {[key: string]: string} = {
  'wealth gaps': 'wealthgaps',
  'international artwork': 'deck',
  'average income of rich': 'richincome',
  'beverage sales': 'soda',
  'freedom from taxation': 'lowtax',
  'gambling': 'gambling',
  obesity: 'fat',
  'average disposable income': 'dispincome',
  'death rate': 'death',
  weaponization: 'armed',
  'insurance': 'insurance',
  'automobile manufacturing': 'auto',
  crime: 'crime',
  charmlessness: 'avoided',
  'pizza delivery': 'pizza',
  'retail': 'retail',
  corruption: 'corrupt',
  'cheese exports': 'cheese',
  'basket weaving': 'basket',
  'furniture restoration': 'furniture',
  'political apathy': 'apathetic',
  'average income': 'income',
  rudeness: 'rude',
  'economic output': 'gdp',
  economy: 'economy',
  'scientific advancement': 'advanced',
  'youth rebelliousness': 'rebelyouth',
  'timber woodchipping': 'timber',
  'mining': 'mining',
  'sector: manufacturing': 'manufacturing',
  culture: 'culture',
  'sector: agriculture': 'agriculture',
  'book publishing': 'publishing',
  'information technology': 'tech',
  intelligence: 'smart',
  employment: 'employed',
  'arms manufacturing': 'arms',
  'business subsidization': 'business',
  nudity: 'nude',
  population: 'population',
  'government size': 'govt',
  secularism: 'godforsaken',
  'black market': 'blackmarket',
  'economic freedom': 'pro-market',
  'world assembly endorsements': 'endorsed',
  'public education': 'educated',
  'human development index': 'hdi',
  'ideological radicality': 'extreme',
  'recreational drug use': 'drugs',
  'trout fishing': 'fish',
  'social conservatism': 'conservative',
  'public healthcare': 'healthcare',
  'foreign aid': 'aid',
  authoritarianism: 'authoritarian',
  'civil rights': 'liberal',
  'political freedoms': 'polifree',
  averageness: 'average',
  influence: 'influence',
  residency: 'stationary',
  patriotism: 'patriotism',
  'average income of poor': 'poorincome',
  religiousness: 'devout',
  'public transport': 'publictransport',
  'defense forces': 'defense',
  ignorance: 'stupid',
  inclusiveness: 'inclusive',
  'food quality': 'foodquality',
  'law enforcement': 'police',
  primitiveness: 'primitive',
  pacifism: 'peace',
  cheerfulness: 'happy',
  niceness: 'nice',
  compassion: 'compassionate',
  welfare: 'welfare',
  integrity: 'leastcorrupt',
  'eco friendliness': 'eco-govt',
  tourism: 'tourism',
  'environmental beauty': 'environment',
  compliance: 'lowcrime',
  taxation: 'hightax',
  safety: 'safe',
  weather: 'weather',
  health: 'healthy',
  lifespan: 'life',
  'income equality': 'equality',
  'sans': 'no_badge'
};