version: "3.9"
services:
  queries:
    build:
      context: .
    container_name: queries
    volumes:
      - ./cards.db:/app/cards.db
      - ./app.log:/app/app.log
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "-s",
          "-o",
          "/dev/null",
          "https://new.sideroca.com/health",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
      - reverse-proxy
  queriescache:
    restart: always
    image: redis:alpine
    container_name: queriescache
    volumes:
      - queriescache:/data
    networks:
      - reverse-proxy
volumes:
  queriescache: null
networks:
  reverse-proxy:
    external: true
